pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                dir('own-project') {
                    sh 'docker build -t hello-java .'
                }
            }
        }
        stage('Run Container') {
            steps {
                sh 'docker run --rm hello-java'
            }
        }
    }
}

